### ISSUE TITLE
ThemedPanel has a graphical glitch when being pulled back into the screen

### ISSUE THREAD

**Issue by Kermalis** [Kermalis/GBAMusicStudio#12]
![image](https://user-images.githubusercontent.com/29823718/44312667-cabdf200-a3c9-11e8-81fe-0a91b942d741.png)

![image](https://user-images.githubusercontent.com/29823718/44312674-da3d3b00-a3c9-11e8-8d0e-d5d4d1274b16.png)

**Comment by Tulu473** [comment]
FIX THE FUCKING BUG IN HERE, KTHX 
![image](https://user-images.githubusercontent.com/39826439/48983470-13beca00-f0ce-11e8-8f23-0d9290ca3e4b.png)
