### ISSUE TITLE
Mother 1+2 (Japan) related

### ISSUE THREAD

**Issue by John-Enigma** [Kermalis/GBAMusicStudio#19]
@Kermalis 

Hello. My name is John Enigma, and I'm part of the [Mother 2 GBA VWF Project](https://github.com/jeffman/Mother2GbaTranslation) by Jeffman. Right now, progress has been running smoothly on our Discord, and not only are we porting, and bugfixing, the entire script of EarthBound to M2GBA. There are also sub-projects unrelated to Mother 2 GBA, which is a recolorization, and a music & sound restoration. The latter is actually more important than the colors one. Why? Because Mother 2 GBA's music sounds like an ear-deafening mess, compared to the original (EarthBound). 

One of the members of the translation team is interested in restoring the music, but the problem is that there are no available builds, or a way to compile the app via the source code. Can you help us out on that?

Also, I have one small personal question: does this program have the ability to edit music of the Mother 1 portion of Mother 1+2? 

Here's a link to our Discord: https://discord.gg/FuBXVV

**Comment by SomeShrug** [comment]
You can open the project in Visual Studio 2017 and compile there for Windows x64/x86.

From there you will have to add a song entry into the config YAML file.
Make sure your hex-codes are lowercase or the program will fail.
Make sure you also have the .NET v4.7.1 development SDK or higher.

**Comment by Kermalis** [comment]
Closing because I joined the discord server
