### ISSUE TITLE
Pokemon FireRed (1.1) Music is named incorrectly and incorrectly ordered

### ISSUE THREAD

**Issue by yoshikirby43** [Kermalis/GBAMusicStudio#28]
I tried a 1.0 and its correctly ordered  and named but not for 1.1 would this be fixable?

**Comment by Kermalis** [comment]
They are different ROMs, so the music is not in the same place, so for now you either have to edit the config or just use 1.0 (and pretty much the entire hacking community uses 1.0 versions of things anyway)

**Comment by Kermalis** [comment]
This is now a feature as of 4deed92
